// Short lines shown on the "summoning" loading screen — a mix of gameplay tips
// and Magic flavour to keep the player engaged while a fresh hand is drawn.
export const SUMMONING_TEXTS: string[] = [
  // Gameplay tips
  'Guess fast — the sooner you answer, the more points you score.',
  'Each second peels back another layer of the card.',
  'Stuck? The artwork alone often gives it away.',
  "The mana cost surfaces late — don't wait for it.",
  'Popular pool = Commander staples. All cards = the deep cuts.',
  'One wrong guess ends the card. Trust your gut.',
  'Type line first, then the rules text — read clues as they appear.',
  'Power and toughness hint at creatures you already know.',
  'Speed beats certainty: an early answer outscores a late one.',
  'Pace yourself — the clock is merciless.',
  'Trust the silhouette before the text loads.',
  'Recognise the artist? That can be a clue too.',
  'The rarity glow hints at how famous a card is.',
  'Big mana value? Probably a finisher.',
  'When in doubt, pick the name that fits the colours.',
  'A steady streak beats a lucky guess.',
  'Your fastest correct answer is worth the most.',
  'Lands, creatures and spells each have a distinct look.',
  'Old frames and new — the art spans decades.',
  'Breathe. The card will reveal itself.',
  // Reassurance that cards are always fresh
  'Every restart deals a brand-new hand.',
  'No two games pull the same cards.',
  // Magic flavour
  'Shuffling the multiverse…',
  'Drawing from ten thousand planes…',
  'The Blind Eternities stir.',
  'Tapping lands for arcane power…',
  'A planeswalker spark ignites.',
  'Somewhere, a Llanowar Elf taps for green.',
  'The Gatewatch is watching.',
  'Counterspell? Too late — the cards are coming.',
  'Reshuffling fate…',
  'The stack resolves in your favour.',
  'Channelling mana from distant worlds…',
  'A goblin lights the fuse…',
  'The library whispers your next card.',
  'Even the Eldrazi await your guess.',
  'Brewing a fresh hand…',
  'Cracking a fetchland for the perfect draw…',
  'Untapping for a new turn…',
  'The summoning is nearly complete.',
];
